version: "2"

networks:
  default:
    external:
      name: cjp-demo-environment

services:
  
  proxy:
    container_name: cjp.local
    #https://hub.docker.com/_/nginx/
    image: nginx:1.19.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      - ./certs/cjp.local.key:/etc/nginx/cjp.local.key:ro
      - ./certs/cjp.local.crt:/etc/nginx/cjp.local.crt:ro
    depends_on: #to force proxy to start after:
      - cjoc

  idp:
    container_name: idp
    image: kristophjunge/test-saml-idp
    ports:
      - "8443:8443"
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=https://cjp.local/cjoc/securityRealm/finishLogin
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=https://cjp.local/cjoc/securityRealm/finishLogin
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=https://cjp.local/cjoc/securityRealm/finishLogin
    volumes:
      - ./simplesamlphp/config:/var/www/simplesamlphp/config
      - ./simplesamlphp/config/local-users.php:/var/www/simplesamlphp/config/authsources.php
      - ./simplesamlphp/metadata:/var/www/simplesamlphp/metadata
      - ./simplesamlphp/modules/authcrypt-enable:/var/www/simplesamlphp/modules/authcrypt/enable
      - ./simplesamlphp/apache2/simplesamlphp.conf:/etc/apache2/sites-available/simplesamlphp.conf
      - ./simplesamlphp/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./simplesamlphp/apache2/ports.conf:/etc/apache2/ports.conf
      - ./certs/idp.local.crt:/etc/ssl/cert/idp.local.crt:ro
      - ./certs/idp.local.key:/etc/ssl/private/idp.local.key:ro
      - ./data/simplesamlphp/logs:/var/log/apache2

  cjoc:
    container_name: cjoc
    #https://hub.docker.com/r/cloudbees/jenkins-operations-center/
    image: cloudbees/jenkins-operations-center:2.249.3.2
    ports:
      - "50000:50000"
    environment:
      JENKINS_SLAVE_AGENT_PORT: "50000"
      JENKINS_HA: "false"
      #https://wiki.jenkins-ci.org/display/JENKINS/Features+controlled+by+system+properties
      JAVA_OPTS: "
        -Dhudson.TcpSlaveAgentListener.hostName=cjoc
        -Dhudson.TcpSlaveAgentListener.port=50000
        -Dhudson.udp=-1
        -Dhudson.DNSMultiCast.disabled=true
        -Djava.awt.headless=true
        -Djavax.net.ssl.trustStore=/var/jenkins_home/cacerts
        -Djavax.net.ssl.trustStorePassword=changeit
        -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York
        "
      JENKINS_OPTS: "--prefix=/cjoc"
    volumes:
      - ./data/cjoc:/var/jenkins_home
      - ./data/backups:/backups
      - ./certs/cacerts:/var/jenkins_home/cacerts
